### PR TITLE
Fix the incorrect thumbnails for albums issue

### LINKED ISSUE #1183: Incorrect thumbnails for albums
**Describe the bug**
Photoview shows completely incorrect album thumbnails.
I have my own fork, where I apply the same version updates, but didn't merge it with the master repo for several months, and I see that it works correctly with the same DB and cache.
I've checked logs in docker and the browser's console - there are no errors, it just returns completely unrelated thumbnails or shows no thumbnails for albums. Maybe there are other side effects, which I didn't notice...
I investigated it during this weekend and even recreated the DB/cache twice from scratch: 1st by running the initial scan from my forked image and then switching to the master, and 2nd - by the master image - no impact, reproduced the issue all the time when served by the master image.

**To Reproduce**
1. Create a new Photoview instance or use the existing one
2. Scan a pretty large and complex gallery of photos and videos with many albums and sub-albums
3. Once the scan is done, navigate through the Albums section and pay attention to the thumbnails
4. See issue: many thumbnails are not from the content inside of the album, some are missing

**Expected behavior**
All thumbnails have to be from the album's content.

**Screenshots**
As the issue is found in my PROD instance, I cannot share anything.

**Your environment:**

 - Are you using Docker? [yes]
 - Database [PostgreSQL 16-alpine]
 - Browser [Brave]
 - Version [master (sha-0f19345)]

### PR DESCRIPTION
**Pull request by kkovaletp**
Fixes #1183 by implementing the fix suggested by @AndGem.

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved the logic for selecting album thumbnails, ensuring more accurate and reliable thumbnail selection for albums and their child albums.

- **Tests**
  - Added comprehensive tests to verify thumbnail selection across various album and media scenarios, including albums with covers, child albums, and empty albums.

### CODE REVIEW

File: api/graphql/models/album_test.go [hunk 1]
```diff
@@ -124,3 +124,62 @@ func TestAlbumGetChildrenAndParents(t *testing.T) {
 	})
 
 }
+
+func TestAlbumThumbnail(t *testing.T) {
```
Comment (kkovaletp) [inline api/graphql/models/album_test.go:128]: @coderabbitai, after this new test function was added, the tests are failing on CI with the next error:
```
2025/05/01 08:34:22 /app/api/graphql/models/album_test.go:134 ERROR: insert or update on table "media" violates foreign key constraint "fk_media_album" (SQLSTATE 23503)
[2.292ms] [rows:0] INSERT INTO "media" ("created_at","updated_at","title","path","path_hash","album_id","exif_id","date_shot","type","video_metadata_id","side_car_path","side_car_hash","blurhash") VALUES ('2025-05-01 08:34:22.267','2025-05-01 08:34:22.267','','thumb.jpg','233d32ad129990d4c583c6db55ea5e17',0,NULL,'0000-00-00 00:00:00','',NULL,NULL,NULL,NULL) RETURNING "id"
    album_test.go:134: 
        	Error Trace:	/app/api/graphql/models/album_test.go:134
        	Error:      	Received unexpected error:
        	            	ERROR: insert or update on table "media" violates foreign key constraint "fk_media_album" (SQLSTATE 23503)
        	Test:       	TestAlbumThumbnail
--- FAIL: TestAlbumThumbnail (0.14s)
```
Please carefully analyze the PR in the context of all the project, and suggest a consistent and reliable fix

Comment (kkovaletp) [reply api/graphql/models/album_test.go:128]: @coderabbitai, thanks, your fix works.
Can you please review the added testing function with testcases and let me know whether it covers the change in the product code well, or do you see some missing cases?
Do you have some other suggestions for the new testing code?

Comment (kkovaletp) [reply api/graphql/models/album_test.go:128]: @coderabbitai, thanks for your suggestions.
Did you consider the scan job pipeline's algorithm when suggesting these improvements? I guess there are several impossible scenarios in your list. Please carefully analyze the scan job code and double-check that your scenarios are valid and can happen in real-life scenarios.
Your suggestion for an empty album test contains some assumptions about the product behavior in the final asserts. You have access to all the product code to figure out the exact expectations.

Comment (kkovaletp) [reply api/graphql/models/album_test.go:128]: @coderabbitai, thanks for the 2 additional tests, but the empty album test fails with the next output:
```
=== RUN   TestAlbumThumbnail/Empty_album_with_no_media

2025/05/01 10:38:43 /app/api/graphql/models/album_test.go:200
[0.841ms] [rows:1] INSERT INTO "albums" ("created_at","updated_at","title","parent_album_id","path","path_hash","cover_id") VALUES ('2025-05-01 10:38:43.235','2025-05-01 10:38:43.235','Empty album',NULL,'/empty','70b0558f0fa5d3355db2fadb88ca91ce',NULL) RETURNING "id"

2025/05/01 10:38:43 /app/api/graphql/models/album.go:105
[0.695ms] [rows:0] 
		WITH RECURSIVE sub_albums AS (
			SELECT id FROM albums WHERE id = 10
			UNION ALL
			SELECT children.id FROM albums AS children
			INNER JOIN sub_albums ON children.parent_album_id = sub_albums.id
		)
		SELECT * FROM media
		WHERE media.album_id IN (SELECT id FROM sub_albums)
		LIMIT 1
	
    album_test.go:206: 
        	Error Trace:	/app/api/graphql/models/album_test.go:206
        	Error:      	Expected nil, but got: &models.Media{Model:models.Model{ID:0, ModelTimestamps:models.ModelTimestamps{CreatedAt:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), UpdatedAt:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC)}}, Title:"", Path:"", PathHash:"", AlbumID:0, Album:models.Album{Model:models.Model{ID:0, ModelTimestamps:models.ModelTimestamps{CreatedAt:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), UpdatedAt:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC)}}, Title:"", ParentAlbumID:(*int)(nil), ParentAlbum:(*models.Album)(nil), Owners:[]models.User(nil), Path:"", PathHash:"", CoverID:(*int)(nil)}, ExifID:(*int)(nil), Exif:(*models.MediaEXIF)(nil), MediaURL:[]models.MediaURL(nil), DateShot:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Type:"", VideoMetadataID:(*int)(nil), VideoMetadata:(*models.VideoMetadata)(nil), SideCarPath:(*string)(nil), SideCarHash:(*string)(nil), Faces:[]*models.ImageFace(nil), Blurhash:(*string)(nil)}
        	Test:       	TestAlbumThumbnail/Empty_album_with_no_media
        	Messages:   	Album with no media should return nil thumbnail
```
It looks like your assumption of returning Nil is incorrect. Please fix the test consistently

**Comment by kkovaletp** [comment]
@googollee, please review this PR with the fix of a critical issue.

**Comment by kkovaletp** [comment]
https://github.com/kkovaletp/photoview/pull/442 - the same PR to my forked repo - just for reference, as CodeRabbit gave me some additional suggestions there)

File: api/graphql/models/album_test.go [hunk 2]
```diff
@@ -124,3 +124,243 @@ func TestAlbumGetChildrenAndParents(t *testing.T) {
...
+			Path:  "/empty",
+		}
+		if !assert.NoError(t, db.Save(&emptyAlbum).Error) {
+			return
+		}
+
+		result, err := emptyAlbum.Thumbnail(db)
+		assert.NoError(t, err)
+		assert.Nil(t, result, "Empty albums should have nil thumbnail")
+	})
```
[the remark this answers is not in the document]
Comment (kkovaletp) [reply api/graphql/models/album_test.go:207]: @coderabbitai, please carefully analyze the latest commit. There is a consistent change in the product code and in the tests to return Nil in this case, because the frontend expects Null instead of an empty album
